#프로젝트 이름 설정 예시
spring:
  application:
    name: basic
#아래는 jdbc의 기본 db관련 설정인데, jdbc뿐만 아니라 mybatis, jap 등 spring의 대부분의 db기술에 동일하게 사용
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/board
    username : root
    password : 1234
  jpa:
    database: mysql
    #    innoDB를 쓰겠다 라는 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    # ddl문을 자동생성 여부 true. 테이블은 자동생성(반영)해주나, 스키마는 반드시 사전에 생성 필요.
    generate-ddl: true
    # jpa의 실질적인 구현체는 hibernate
    hibernate:
      # create : 매번(서버재시작) table을 drop 후 재생성
      # update : entity 변경사항만 alter를 적용하고 기존데이터 유지.
      # validate : 실제DB와의 차이점을 check만 하고 ddl문 실행X, 콘솔로만 변경사항 출력
      ddl-auto: create
#    콘솔창에 ddl, dml 등의 쿼리를 출력하여 보여주는 옵션
    show_sql : true

# mapper 파일(mybatis의 쿼리파일)의 위치를 명시. 기본적으로 resource 폴더는 default
#mybatis:
#  mapper-locations: classpath:/mapper/**/*.xml

#서버 포트 기본값은 8080
server:
  port: 8080

