#프로젝트 이름 설정 예시
#spring.application.name=basic

#서버 포트 기본값은 8080입니다
#server.port=8080


server:
  port: 8080

spring:
  config:
    active:
      on-profile: local
  # 아래는 jdbc의 기본 db 관련 설정인데, jdbc 뿐만 아니라 mybatis / jpa 등 spring의 대부분의 DB 기술에 동일하게 사용
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/board
    username: root
    password: 1234

  jpa:
    database: mysql
    #    innoDB 사용한다는 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    DDL문 자동 생성 설정 여부. 테이블은 자동 생성(반영) 해주지만 스키마는 반드시 사전에 생성 필요
    generate-ddl: true
    #    ⭐ JPA(인터페이스) 의 실질적인 구현체는 hibernate
    hibernate:
      #      create : 매번 테이블을 drop 후 재생성
      #      update : entity 변경 사항만 alter를 적용하고 기존 데이터 유지
      #      validate : 실제 DB와의 차이점을 체크만 하고 DDL 문 실행X, 콘솔로만 변경 사항 출력
      ddl-auto: update
    #      콘솔창에 DDL, DML 등의 쿼리를 출력하여 보여주는 옵션
    show_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    #    debug, info, error 로그 출력
    root: info

# mapper 파일 (mybatis의 쿼리 파일)의 위치를 명시하고 scan. 기본적으로 resource 폴더는 default
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml